apiVersion: apps/v1
kind: Deployment
metadata:
  name: angler-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angler-app
  template:
    metadata:
      labels:
        app: angler-app
    spec:
      containers:
      - name: app
        image: app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: angler-app-service
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30000
  selector:
    app: angler-app
